/****************************************************************************
** 
**  V O I D O N E   E N G I N E
**  High-Performance QML & C++ Core
** 
**  Copyright (C) 2026 VoidOne-App
**  Repository: https://github.com/VoidOne-App/VoidOne
**  SPDX-License-Identifier: MIT
** 
****************************************************************************/

#include <QGuiApplication>
#include <QQmlApplicationEngine>
#include <QQmlContext>
#include <QCommandLineParser>
#include <QStandardPaths>
#include <QLockFile>
#include <QDir>
#include <QFile>
#include <QTextStream>
#include <QDateTime>
#include <QDebug>

#include <exception>

// C++ Backend Modules
#include "Database.h"
#include "GameModel.h"
#include "SaveBackupManager.h"
#include "SteamScanner.h"
#include "TranslationManager.h"

// Auto-generated version header generated by CMake — do not edit manually
#include "VoidOneVersion.h"

namespace {

// ============================================================================
// File-Backed Logging System
// ============================================================================
// Redirects logs to a persistent file under AppData/logs while echoing output
// to standard error stream (stderr). Includes automatic log rotation (.old).
// ============================================================================

QFile g_logFile;

QString logDirectoryPath()
{
    return QStandardPaths::writableLocation(QStandardPaths::AppDataLocation) + "/logs";
}

void voidOneMessageHandler(QtMsgType type, const QMessageLogContext &context, const QString &message)
{
    Q_UNUSED(context)

    const char *levelTag = "INFO ";
    switch (type) {
        case QtDebugMsg:    levelTag = "DEBUG"; break;
        case QtInfoMsg:     levelTag = "INFO "; break;
        case QtWarningMsg:  levelTag = "WARN "; break;
        case QtCriticalMsg: levelTag = "CRIT "; break;
        case QtFatalMsg:    levelTag = "FATAL"; break;
    }

    const QString line = QStringLiteral("[%1] [%2] %3")
        .arg(QDateTime::currentDateTime().toString("yyyy-MM-dd HH:mm:ss"))
        .arg(levelTag)
        .arg(message);

    // Echo to console/stderr
    fprintf(stderr, "%s\n", qPrintable(line));
    fflush(stderr);

    // Write to persistent log file
    if (g_logFile.isOpen()) {
        QTextStream stream(&g_logFile);
        stream << line << Qt::endl;
    }

    if (type == QtFatalMsg) {
        abort();
    }
}

bool initializeLogFile()
{
    const QString dirPath = logDirectoryPath();
    QDir().mkpath(dirPath);

    const QString currentPath = dirPath + "/voidone.log";
    const QString previousPath = dirPath + "/voidone.log.old";

    // Rotate previous log file
    QFile::remove(previousPath);
    QFile::rename(currentPath, previousPath);

    g_logFile.setFileName(currentPath);
    return g_logFile.open(QIODevice::WriteOnly | QIODevice::Text);
}

} // namespace

int main(int argc, char *argv[])
{
    // 1. Core Application Metadata Configuration
    QCoreApplication::setOrganizationName("VoidOne-App");
    QCoreApplication::setOrganizationDomain("voidone.app");
    QCoreApplication::setApplicationName("VoidOne");
    QCoreApplication::setApplicationVersion(VOIDONE_VERSION_DISPLAY);

    QGuiApplication app(argc, argv);

    // 2. Command Line Argument Parser
    QCommandLineParser parser;
    parser.setApplicationDescription("VoidOne — a lightweight, open-source PC game launcher.");
    parser.addHelpOption();
    parser.addVersionOption();

    QCommandLineOption verboseOption(
        QStringList() << "v" << "verbose",
        "Enable verbose debug logging."
    );
    parser.addOption(verboseOption);
    parser.process(app);

    // 3. Initialize File-Backed Logging Handler
    const bool logFileReady = initializeLogFile();
    qInstallMessageHandler(voidOneMessageHandler);

    if (!logFileReady) {
        qWarning() << "[VoidOne] Could not open log file — continuing with console-only logging.";
    }

    qDebug() << "\n[VoidOne] =========================================";
    qDebug() << "[VoidOne] Boot sequence initiated... Version:" << QCoreApplication::applicationVersion();
    qDebug() << "[VoidOne] Log file:" << logDirectoryPath() + "/voidone.log";

    // 4. Single-Instance Protection (Prevents concurrent SQLite lock conflicts)
    QLockFile singleInstanceLock(
        QStandardPaths::writableLocation(QStandardPaths::AppDataLocation) + "/voidone.lock"
    );
    singleInstanceLock.setStaleLockTime(0); // Ignore stale lock files from prior crashes

    if (!singleInstanceLock.tryLock(100)) {
        qCritical() << "[VoidOne] Another instance of VoidOne is already running. Exiting.";
        return -1;
    }

    // 5. Main Execution Flow wrapped in Global Exception Handler
    try {
        // Initialize Database Engine
        if (!Database::initialize()) {
            qCritical() << "[VoidOne] FATAL: Failed to initialize the SQLite database.";
            return -1;
        }
        qDebug() << "[VoidOne] SQLite Database mounted successfully.";

        // Instantiate Backend Controller Objects
        GameModel gameModel;
        gameModel.loadGamesFromDatabase();

        SaveBackupManager saveBackupManager;
        SteamScanner steamScanner;
        TranslationManager trManager;

        qDebug() << "[VoidOne] Backend controllers instantiated.";

        // Initialize QML Application Engine
        QQmlApplicationEngine engine;

        // Expose C++ Context Properties to QML Engine
        QQmlContext *context = engine.rootContext();
        context->setContextProperty("gameModel", &gameModel);
        context->setContextProperty("saveBackupManager", &saveBackupManager);
        context->setContextProperty("steamScanner", &steamScanner);
        context->setContextProperty("trManager", &trManager);

        qDebug() << "[VoidOne] Context properties injected into QML.";

        // Safety Signal Connections
        QObject::connect(
            &engine,
            &QQmlApplicationEngine::objectCreationFailed,
            &app,
            []() {
                qCritical() << "[VoidOne] FATAL: Failed to create root QML objects.";
                QCoreApplication::exit(-1);
            },
            Qt::QueuedConnection
        );

        QObject::connect(&app, &QCoreApplication::aboutToQuit, []() {
            qDebug() << "[VoidOne] Shutdown sequence complete. Goodbye.";
        });

        // Load Main QML View Component
        qDebug() << "[VoidOne] Loading primary QML module (Main.qml)...";
        engine.loadFromModule("VoidOne", "Main");

        if (engine.rootObjects().isEmpty()) {
            qCritical() << "[VoidOne] FATAL: QML Engine is empty after load.";
            return -1;
        }

        qDebug() << "[VoidOne] UI rendered successfully. Entering Event Loop.";
        qDebug() << "[VoidOne] =========================================\n";

        return app.exec();

    } catch (const std::exception &ex) {
        qCritical() << "[VoidOne] FATAL: Unhandled exception:" << ex.what();
        return -1;
    } catch (...) {
        qCritical() << "[VoidOne] FATAL: Unknown unhandled exception.";
        return -1;
    }
}
